### ISSUE TITLE
The system tray is not supported on the current platform

### ISSUE THREAD

**Issue by d1Bihkte** [amir1376/ab-download-manager#126]
Operating system: Ubuntu 24.04.1 LTS | X11
This appears when login to user account or resume from lock screen

![image](https://github.com/user-attachments/assets/45bc04cf-0048-42dc-a2bf-18a30c21409f)

###### App Info
```
appVersion = 1.1.0
platform = Linux
```
###### Exception
```
java.lang.UnsupportedOperationException: The system tray is not supported on the current platform.
    at java.desktop/java.awt.SystemTray.getSystemTray(Unknown Source)
    at java.desktop/sun.awt.X11.XTrayIconPeer$4$1.run(Unknown Source)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
    at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
    at java.base/java.security.AccessController.doPrivileged(Unknown Source)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
    at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
    at java.base/java.security.AccessController.doPrivileged(Unknown Source)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

```

**Comment by amir1376** [comment]
@d1Bihkte Thanks for reporting this. I will test it

**Comment by MapleHe** [comment]
@amir1376  
Hi, 

Thanks for the amazing software.

I have the similar issue on ubuntu 22.04.5 LTS , X11.

Also, when I start the application, it shows as a black square on the tray bar.
The action "Exit" of this tray icon opens the main window instead of quits the application.

And the tray icon doesn't work properly when there are multiple arranged monitor.

![image](https://github.com/user-attachments/assets/be8c45f7-fcd8-4526-9741-150b9d62969a)


BTW, if I use ["Window-list"](https://extensions.gnome.org/extension/602/window-list/) gnome shell extension, there will be an extra "JavaEmbeddedFrame" item in the bar. This item won't disappear even when I close the main application window.

![image](https://github.com/user-attachments/assets/4efe10ae-06ec-42a7-a361-ee7d237acafc)

**Comment by amir1376** [comment]
@MapleHe Hi there
> when I start the application, it shows as a black square on the tray bar.
The action "Exit" of this tray icon opens the main window instead of quits the application.

this is a known issue which reported before. the option menu is a custom undecorated window. and somehow it will not focused in Linux. when you press on it simply run the program... if you press a right click on the option menu you then will see that menu items can react to mouse hover and also work correctly. 
because of that I need to use linux native tray option menu later.

> BTW, if I use ["Window-list"](https://extensions.gnome.org/extension/602/window-list/) gnome shell extension, there will be an extra "JavaEmbeddedFrame" item in the bar. This item won't disappear even when I close the main application window.

Did you use the installation script?

**Comment by MapleHe** [comment]
I use the `.deb` file published in the release page, tag `1.4.2`, . And after `dpkg -i`, the `dpkg -l` shows the version number  `1.4.2-1` 

<https://github.com/amir1376/ab-download-manager/releases/download/v1.4.2/ABDownloadManager_1.4.2_linux.deb>

**Comment by amir1376** [comment]
> I used the `.deb` file published in the release page, tag `1.4.2`, . And after `dpkg -i`, the `dpkg -l` shows the version number `1.4.2-1`
> 
> https://github.com/amir1376/ab-download-manager/releases/download/v1.4.2/ABDownloadManager_1.4.2_linux.deb

this is related to Desktop file.

if you use the [installation script](https://github.com/amir1376/ab-download-manager?tab=readme-ov-file#installation) it will fix that.

before that make sure to remove the old `deb` installation

**Comment by MapleHe** [comment]
@amir1376  

Thanks for your quick reply.

As I understand, the script is just downloading a pre-built binary file, and run this binary file to start the application.

I tried and still got the "JavaEmbeddedFrame", and  the commandline output is:

```text
SLF4J(W): No SLF4J providers were found.
SLF4J(W): Defaulting to no-operation (NOP) logger implementation
SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.
```

I would like to test if more debug messages are required, or there is any other possible solution.
And please tell me if it's necessary to create a new issue.

**Comment by amir1376** [comment]
> @amir1376
> 
> Thanks for your quick reply.
> 
> As I understand, the script is just downloading a pre-built binary file, and run this binary file to start the application.


You are correct but it also creates a .desktop entry file which can properly show icon of the app in your desktop as you can see [here](https://github.com/amir1376/ab-download-manager/blob/8f64aa51e73cd42f07342b6d2dd225a6b1d8cf99/scripts/install.sh#L64)

**Comment by MapleHe** [comment]
> > @amir1376
> > Thanks for your quick reply.
> > As I understand, the script is just downloading a pre-built binary file, and run this binary file to start the application.
> 
> @MapleHe You are correct but it also creates a .desktop entry file which can properly show icon of the app in your desktop as you can see [here](https://github.com/amir1376/ab-download-manager/blob/8f64aa51e73cd42f07342b6d2dd225a6b1d8cf99/scripts/install.sh#L64)

@amir1376  

Yes I understand. I mean, the icon now works well in the application page, and the task switching (`alt+tab`), but still not in the top tray bar.

![image](https://github.com/user-attachments/assets/638b97cb-1678-47b5-8601-9594430d8631)

Not sure whether it's because of my system-wide customization, or some other issues.

Anyway, thanks for your suggestions.

**Comment by amir1376** [comment]
@MapleHe The tray bar is buggy in Linux for now. and should be fixed by me.
I mentioned about the installation script to fix the desktop icon!

**Comment by MapleHe** [comment]
@amir1376   
Sorry for my misunderstanding and letting you waste time on explaining.
You're correct, I've noticed that it fix the desktop icon as expected, which is nice.

Actually my original question was not about the icon, but the weird "JavaEmbeddedFrame" task,

![image](https://github.com/user-attachments/assets/4efe10ae-06ec-42a7-a361-ee7d237acafc)

Like what they discussed in
- <https://forums.linuxmint.com/viewtopic.php?t=103890>
- <https://github.com/linuxmint/cinnamon/issues/728>

As you mentioned, you will fix the tray issue, which I assume will also fix the "JavaEmbeddedFrame".

Thanks a lot for your patience.
All solved.

**Comment by EldrinSMP** [comment]
I installed via the installation script today and got a similat error, albeit with a LOT more lines. Upon rebooting it's fixed. though I still have the taskbar issue. I'm going to uninstall and go back to one of the Aur builds, I think, for ease of updating.

**Comment by ShazidMashrafi** [comment]
Hi there, I am also facing this issue on my Ubuntu 24.10 (wayland). App version is 1.5.0. 
Is there a temporary fix or any method to remove this window popping up?
Thanks again for the amazing software.

**Comment by amir1376** [comment]
> Is there a temporary fix or any method to remove this window popping up?
Unfortunately there is no fix yet. I need to fix that bug.

**Comment by amir1376** [comment]
it is fixed now. and will be available in next release.

**Comment by BISWA63** [comment]
I am again getting this error in Fedora 43 Workstation everytime I switch apps or just simply navigate into my overview/workspaces
